# Generated by Django 4.2.3 on 2023-12-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primarychild',
            old_name='occupation',
            new_name='caregiverAge',
        ),
        migrations.RenameField(
            model_name='primarychild',
            old_name='parentName',
            new_name='caregiverContact',
        ),
        migrations.RenameField(
            model_name='primarychild',
            old_name='address',
            new_name='houseNumberAndStreet',
        ),
        migrations.RemoveField(
            model_name='primarychild',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='primarychild',
            name='relationship',
        ),
        migrations.AddField(
            model_name='primarychild',
            name='birthOrder',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='birthWeight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='caregiverFirstName',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='caregiverMiddleName',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='caregiverOccupation',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='caregiverRelationship',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='caregiverReligion',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='caregiverSuffix',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='caregiverSurname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='fatherAge',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='fatherContact',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='fatherEthnicity',
            field=models.CharField(choices=[('Others', 'Others'), ('Aggay', 'Aggay'), ('Akeanon/Aklanon', 'Akeanon/Aklanon'), ('Apayao/Yapayao', 'Apayao/Yapayao'), ('Ayangan', 'Ayangan'), ('Balangao/Baliwon', 'Balangao/Baliwon'), ('Bikol/Bicol', 'Bikol/Bicol'), ('Bisaya/Binisaya', 'Bisaya/Binisaya'), ('Bontok/Binontok', 'Bontok/Binontok'), ('Cebuano', 'Cebuano'), ('Hamtikanon', 'Hamtikanon'), ('Hiligaynon,Ilonggo', 'Hiligaynon,Ilonggo'), ('Ibaloi/Inibaloi', 'Ibaloi/Inibaloi'), ('Ibanag', 'Ibanag'), ('Ibontoc', 'Ibontoc'), ('Ifugao', 'Ifugao'), ('Kalanguya/Ikalahan', 'Kalanguya/Ikalahan'), ('Ilocano', 'Ilocano'), ('Iranon', 'Iranon'), ('Itneg', 'Itneg'), ('Kalinga', 'Kalinga'), ('Kankanai/Kankanaey', 'Kankanai/Kankanaey'), ('Kapampangan', 'Kapampangan'), ('Karao', 'Karao'), ('Kinalinga', 'Kinalinga'), ('Kiniray-a', 'Kiniray-a'), ('Maranao', 'Maranao'), ('Masbateno/Masbatean', 'Masbateno/Masbatean'), ('Pangasinan/Panggalato', 'Pangasinan/Panggalato'), ('Surigaonon', 'Surigaonon'), ('Tagalog', 'Tagalog'), ('Tausug', 'Tausug'), ('Waray', 'Waray')], default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='fatherFirstName',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='fatherMiddleName',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='fatherOccupation',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='fatherReligion',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='fatherSuffix',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='fatherSurname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='firstname',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='lengthOfStay',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='lengthOfStayType',
            field=models.CharField(choices=[('Year/s', 'Year/s'), ('Month/s', 'Month/s'), ('Week/s', 'Week/s')], default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='middlename',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='motherAge',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='motherContact',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='motherEthnicity',
            field=models.CharField(choices=[('Others', 'Others'), ('Aggay', 'Aggay'), ('Akeanon/Aklanon', 'Akeanon/Aklanon'), ('Apayao/Yapayao', 'Apayao/Yapayao'), ('Ayangan', 'Ayangan'), ('Balangao/Baliwon', 'Balangao/Baliwon'), ('Bikol/Bicol', 'Bikol/Bicol'), ('Bisaya/Binisaya', 'Bisaya/Binisaya'), ('Bontok/Binontok', 'Bontok/Binontok'), ('Cebuano', 'Cebuano'), ('Hamtikanon', 'Hamtikanon'), ('Hiligaynon,Ilonggo', 'Hiligaynon,Ilonggo'), ('Ibaloi/Inibaloi', 'Ibaloi/Inibaloi'), ('Ibanag', 'Ibanag'), ('Ibontoc', 'Ibontoc'), ('Ifugao', 'Ifugao'), ('Kalanguya/Ikalahan', 'Kalanguya/Ikalahan'), ('Ilocano', 'Ilocano'), ('Iranon', 'Iranon'), ('Itneg', 'Itneg'), ('Kalinga', 'Kalinga'), ('Kankanai/Kankanaey', 'Kankanai/Kankanaey'), ('Kapampangan', 'Kapampangan'), ('Karao', 'Karao'), ('Kinalinga', 'Kinalinga'), ('Kiniray-a', 'Kiniray-a'), ('Maranao', 'Maranao'), ('Masbateno/Masbatean', 'Masbateno/Masbatean'), ('Pangasinan/Panggalato', 'Pangasinan/Panggalato'), ('Surigaonon', 'Surigaonon'), ('Tagalog', 'Tagalog'), ('Tausug', 'Tausug'), ('Waray', 'Waray')], default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='motherFirstName',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='motherMiddleName',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='motherOccupation',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='motherReligion',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='motherSuffix',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='motherSurname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='sitio',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='primarychild',
            name='surname',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='childhealthinfo',
            name='disability',
            field=models.CharField(choices=[('Cleft Palate', 'Cleft Palate'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Congenital Heart Disease', 'Congenital Heart Disease'), ('Hydrocepalus', 'Hydrocepalus'), ('Down Syndrome', 'Down Syndrome'), ('Global Development Delay', 'Global Development Delay'), ('Others', 'Others')], default='Not specified', max_length=100),
        ),
    ]
