# Generated by Django 4.2.6 on 2023-10-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='bpe',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='forms',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Not specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='forms',
            name='pt',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='forms',
            name='relationship',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')], default='Not specified', max_length=200),
        ),
    ]
