# Generated by Django 4.2.3 on 2023-10-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='middle_name',
            new_name='middleName',
        ),
    ]
