# Generated by Django 4.2.3 on 2023-10-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='aim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forms',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Not specified', max_length=10),
        ),
    ]
