# Generated by Django 4.2.6 on 2023-11-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('first_barangay', models.CharField(max_length=255)),
                ('second_barangay', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='ethnicity',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), (' M', 'Male'), ('M ', 'Male'), (' F', 'Female'), ('F ', 'Female')], default='Not specified', max_length=10),
        ),
    ]
