# Generated by Django 4.2.6 on 2023-11-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0002_duplicatechild_alter_primarychild_ethnicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatechild',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
