# Generated by Django 4.2.6 on 2023-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0002_primarychild_archive_primarychild_customethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarychild',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), (' M', 'Male'), ('M ', 'Male'), (' F', 'Female'), ('F ', 'Female')], default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='pt',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Transient', 'Transient')], default='', max_length=90),
        ),
    ]
