# Generated by Django 4.2.3 on 2023-10-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0002_forms_aim_alter_forms_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='pt',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Transient', 'Transient')], default='', max_length=30),
        ),
    ]
