# Generated by Django 4.2.6 on 2023-11-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0002_childhealthinfo_weightforage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childhealthinfo',
            old_name='fic',
            new_name='deworming',
        ),
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='deworming1',
        ),
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='deworming2',
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vac',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=10),
        ),
    ]
