# Generated by Django 4.2.3 on 2023-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0002_rename_occupation_primarychild_caregiverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarychild',
            name='motherSuffix',
        ),
        migrations.AlterField(
            model_name='childhealthinfo',
            name='vac',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('None', 'None')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='caregiverSuffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='fatherEthnicity',
            field=models.CharField(choices=[('OTHERS', 'Others'), ('AGGAY', 'Aggay'), ('AKEANON/AKLANON', 'Akeanon/Aklanon'), ('APAYAO/YAPAYAO', 'Apayao/Yapayao'), ('AYANGAN', 'Ayangan'), ('BALANGAO/BALIWON', 'Balangao/Baliwon'), ('BIKOL/BICOL', 'Bikol/Bicol'), ('BISAYA/BINISAYA', 'Bisaya/Binisaya'), ('BONTOK/BINONTOK', 'Bontok/Binontok'), ('CEBUANO', 'Cebuano'), ('HAMTIKANON', 'Hamtikanon'), ('HILIGAYNON,ILONGGO', 'Hiligaynon,Ilonggo'), ('IBALOI/INIBALOI', 'Ibaloi/Inibaloi'), ('IBANAG', 'Ibanag'), ('IBONTOC', 'Ibontoc'), ('IFUGAO', 'Ifugao'), ('KALANGUYA/IKALAHAN', 'Kalanguya/Ikalahan'), ('ILOCANO', 'Ilocano'), ('IRANON', 'Iranon'), ('ITNEG', 'Itneg'), ('KALINGA', 'Kalinga'), ('KANKANAI/KANKANAEY', 'Kankanai/Kankanaey'), ('KAPAMPANGAN', 'Kapampangan'), ('KARAO', 'Karao'), ('KINALINGA', 'Kinalinga'), ('KINIRAY-A', 'Kiniray-a'), ('MARANAO', 'Maranao'), ('MASBATENO/MASBATEAN', 'Masbateno/Masbatean'), ('PANGASINAN/PANGGALATO', 'Pangasinan/Panggalato'), ('SURIGAONON', 'Surigaonon'), ('TAGALOG', 'Tagalog'), ('TAUSUG', 'Tausug'), ('WARAY', 'Waray')], default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='fatherSuffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='motherEthnicity',
            field=models.CharField(choices=[('OTHERS', 'Others'), ('AGGAY', 'Aggay'), ('AKEANON/AKLANON', 'Akeanon/Aklanon'), ('APAYAO/YAPAYAO', 'Apayao/Yapayao'), ('AYANGAN', 'Ayangan'), ('BALANGAO/BALIWON', 'Balangao/Baliwon'), ('BIKOL/BICOL', 'Bikol/Bicol'), ('BISAYA/BINISAYA', 'Bisaya/Binisaya'), ('BONTOK/BINONTOK', 'Bontok/Binontok'), ('CEBUANO', 'Cebuano'), ('HAMTIKANON', 'Hamtikanon'), ('HILIGAYNON,ILONGGO', 'Hiligaynon,Ilonggo'), ('IBALOI/INIBALOI', 'Ibaloi/Inibaloi'), ('IBANAG', 'Ibanag'), ('IBONTOC', 'Ibontoc'), ('IFUGAO', 'Ifugao'), ('KALANGUYA/IKALAHAN', 'Kalanguya/Ikalahan'), ('ILOCANO', 'Ilocano'), ('IRANON', 'Iranon'), ('ITNEG', 'Itneg'), ('KALINGA', 'Kalinga'), ('KANKANAI/KANKANAEY', 'Kankanai/Kankanaey'), ('KAPAMPANGAN', 'Kapampangan'), ('KARAO', 'Karao'), ('KINALINGA', 'Kinalinga'), ('KINIRAY-A', 'Kiniray-a'), ('MARANAO', 'Maranao'), ('MASBATENO/MASBATEAN', 'Masbateno/Masbatean'), ('PANGASINAN/PANGGALATO', 'Pangasinan/Panggalato'), ('SURIGAONON', 'Surigaonon'), ('TAGALOG', 'Tagalog'), ('TAUSUG', 'Tausug'), ('WARAY', 'Waray')], default='Not specified', max_length=100),
        ),
    ]
