# Generated by Django 4.2.6 on 2023-10-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0002_alter_forms_bpe_alter_forms_gender_alter_forms_pt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='disability',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
