# Generated by Django 4.2.3 on 2023-10-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_forms_address_forms_bpe_forms_disability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='dow',
            field=models.DateField(blank=True, null=True),
        ),
    ]
