# Generated by Django 4.2.3 on 2023-12-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_alter_primarychild_caregiverage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='primarychild',
            unique_together=set(),
        ),
    ]
