# Generated by Django 4.2.3 on 2023-12-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_remove_primarychild_mothersuffix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarychild',
            name='birthOrder',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
