# Generated by Django 4.2.6 on 2023-11-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_alter_duplicatechild_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicatechild',
            name='birthdate',
        ),
    ]
