# Generated by Django 4.2.6 on 2023-11-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_alter_primarychild_gender_alter_primarychild_pt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='deworming1',
        ),
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='deworming2',
        ),
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='fic',
        ),
        migrations.RemoveField(
            model_name='primarychild',
            name='customEthnicity',
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='deworming',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='lengthForAge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vac',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='weightForAge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='weightForLength',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='childhealthinfo',
            name='bpe',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), (' M', 'Male'), ('M ', 'Male'), (' F', 'Female'), ('F ', 'Female')], default='Not specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='pt',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Transient', 'Transient')], default='', max_length=30),
        ),
    ]
