# Generated by Django 4.2.6 on 2023-11-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_rename_fic_childhealthinfo_deworming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childhealthinfo',
            name='bpe',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='childhealthinfo',
            name='deworming',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='childhealthinfo',
            name='vac',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
