# Generated by Django 4.2.3 on 2023-12-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0004_alter_primarychild_birthorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='childhealthinfo',
            name='dewormingFiveYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='dewormingFourSixYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='dewormingFourYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='dewormingOneSixYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='dewormingOneYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='dewormingThreeSixYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='dewormingThreeYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='dewormingTwoSixYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='dewormingTwoYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vaccinationRemarks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitAOneHTIU',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitATwoHTIUFiveYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitATwoHTIUFourSixYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitATwoHTIUFourYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitATwoHTIUOneSixYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitATwoHTIUOneYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitATwoHTIUThreeSixYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitATwoHTIUThreeYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitATwoHTIUTwoSixYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='vitATwoHTIUTwoYear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
