# Generated by Django 4.2.6 on 2023-11-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0004_remove_childhealthinfo_deworming1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarychild',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), (' M', 'Male'), ('M ', 'Male'), (' F', 'Female'), ('F ', 'Female')], default='Not specified', max_length=100),
        ),
    ]
