# Generated by Django 4.2.3 on 2023-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0004_firstquarter_fourthquarter_secondquarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquarter',
            name='pt',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Transient', 'Transient')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='fourthquarter',
            name='pt',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Transient', 'Transient')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='secondquarter',
            name='pt',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Transient', 'Transient')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='thirdquarter',
            name='pt',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Transient', 'Transient')], default='', max_length=30),
        ),
    ]
