# Generated by Django 4.2.6 on 2023-11-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0004_remove_childhealthinfo_deworming1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childhealthinfo',
            name='disability',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
