# Generated by Django 4.2.6 on 2023-11-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0004_remove_duplicatechild_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duplicatechild',
            old_name='name',
            new_name='full_name',
        ),
    ]
