# Generated by Django 4.2.3 on 2023-11-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0005_childhealthinfo_primarychild_delete_firstquarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarychild',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
