# Generated by Django 4.2.3 on 2023-10-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0005_alter_firstquarter_pt_alter_fourthquarter_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstquarter',
            name='lengthForage',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='firstquarter',
            name='weightForage',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='firstquarter',
            name='weightForlength',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='fourthquarter',
            name='lengthForAge',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='fourthquarter',
            name='weightForAge',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='fourthquarter',
            name='weightForLength',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='secondquarter',
            name='lengthForage',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='secondquarter',
            name='weightForage',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='secondquarter',
            name='weightForlength',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='thirdquarter',
            name='lengthForage',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='thirdquarter',
            name='weightForage',
            field=models.CharField(default='No Info', max_length=255),
        ),
        migrations.AddField(
            model_name='thirdquarter',
            name='weightForlength',
            field=models.CharField(default='No Info', max_length=255),
        ),
    ]
