# Generated by Django 4.2.3 on 2023-10-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0005_alter_forms_address_alter_forms_disability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='bpe',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='dow',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='father_ethnicity',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='height',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='midUpperArmCircumference',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='mother_ethnicity',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='mother_occupation',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='temporary',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='weight',
        ),
    ]
