# Generated by Django 4.2.3 on 2023-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0005_childhealthinfo_dewormingfiveyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childhealthinfo',
            name='vac',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('None', 'None'), ('FIC', 'FIC'), ('CIC', 'CIC'), ('INC', 'INC'), ('None', 'None')], default='No', max_length=10),
        ),
    ]
