# Generated by Django 4.2.6 on 2023-11-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0005_alter_childhealthinfo_disability'),
        ('app_form', '0005_alter_primarychild_gender'),
    ]

    operations = [
    ]
