# Generated by Django 4.2.3 on 2023-12-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0005_alter_primarychild_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarychild',
            name='fullAddress',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
