# Generated by Django 4.2.3 on 2023-11-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0005_alter_firstquarter_pt_alter_fourthquarter_pt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(default='Not specified', max_length=255)),
                ('pt', models.CharField(choices=[('Permanent', 'Permanent'), ('Transient', 'Transient')], default='', max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Not specified', max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('aim', models.IntegerField(default=0)),
                ('parent_name', models.CharField(default='Unknown', max_length=255)),
                ('occupation', models.CharField(default='Unknown', max_length=255)),
                ('relationship', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')], default='Not specified', max_length=200)),
                ('ethnicity', models.CharField(choices=[('Aggay', 'Aggay'), ('Akeanon/Aklanon', 'Akeanon/Aklanon'), ('Apayao/Yapayao', 'Apayao/Yapayao'), ('Ayangan', 'Ayangan'), ('Balangao/Baliwon', 'Balangao/Baliwon'), ('Bikol/Bicol', 'Bikol/Bicol'), ('Bisaya/Binisaya', 'Bisaya/Binisaya'), ('Bontok/Binontok', 'Bontok/Binontok'), ('Cebuano', 'Cebuano'), ('Hamtikanon', 'Hamtikanon'), ('Hiligaynon,Ilonggo', 'Hiligaynon,Ilonggo'), ('Ibaloi/Inibaloi', 'Ibaloi/Inibaloi'), ('Ibanag', 'Ibanag'), ('Ibontoc', 'Ibontoc'), ('Ifugao', 'Ifugao'), ('Kalanguya/Ikalahan', 'Kalanguya/Ikalahan'), ('Ilocano', 'Ilocano'), ('Iranon', 'Iranon'), ('Itneg', 'Itneg'), ('Kalinga', 'Kalinga'), ('Kankanai/Kankanaey', 'Kankanai/Kankanaey'), ('Kapampangan', 'Kapampangan'), ('Karao', 'Karao'), ('Kinalinga', 'Kinalinga'), ('Kiniray-a', 'Kiniray-a'), ('Maranao', 'Maranao'), ('Masbateno/Masbatean', 'Masbateno/Masbatean'), ('Pangasinan/Panggalato', 'Pangasinan/Panggalato'), ('Surigaonon', 'Surigaonon'), ('Tagalog', 'Tagalog'), ('Tausug', 'Tausug'), ('Waray', 'Waray'), ('Other Local Ethnicity', 'Other Local Ethnicity'), ('Chinese', 'Chinese'), ('American/English', 'American/English'), ('Other Foreign Ethnicity', 'Other Foreign Ethnicity'), ('Not Reported', 'Not Reported')], default='Not specified', max_length=200)),
                ('barangay', models.CharField(choices=[('Alapang', 'Alapang'), ('Alno', 'Alno'), ('Ambiong', 'Ambiong'), ('Balili', 'Balili'), ('Bahong', 'Bahong'), ('Beckel', 'Beckel'), ('Betag', 'Betag'), ('Bineng', 'Bineng'), ('Cruz', 'Cruz'), ('Lubas', 'Lubas'), ('Pico', 'Pico'), ('Poblacion', 'Poblacion'), ('Puguis', 'Puguis'), ('Shilan', 'Shilan'), ('Tawang', 'Tawang'), ('Wangal', 'Wangal')], default='Not specified', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('muac', models.FloatField(default=0)),
                ('bpe', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('disability', models.CharField(blank=True, default='', max_length=50)),
                ('purga', models.DateField(blank=True, null=True)),
                ('vac', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.child')),
            ],
        ),
        migrations.DeleteModel(
            name='firstQuarter',
        ),
        migrations.DeleteModel(
            name='fourthQuarter',
        ),
        migrations.DeleteModel(
            name='secondQuarter',
        ),
        migrations.DeleteModel(
            name='thirdQuarter',
        ),
    ]
