# Generated by Django 4.2.3 on 2023-12-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0006_primarychild_fulladdress'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarychild',
            name='currentCaregiver',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
