# Generated by Django 4.2.3 on 2023-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0006_remove_forms_birthdate_remove_forms_bpe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='temporary',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default='', max_length=30),
        ),
    ]
