# Generated by Django 4.2.3 on 2023-11-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0006_rename_lengthforage_childhealthinfo_lengthforage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='lengthForAge',
        ),
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='weightForAge',
        ),
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='weightForLength',
        ),
    ]
