# Generated by Django 4.2.3 on 2023-11-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0006_merge_20231123_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarychild',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Not specified', max_length=100),
        ),
    ]
