# Generated by Django 4.2.3 on 2023-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0007_alter_primarychild_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childhealthinfo',
            old_name='purga',
            new_name='deworming1',
        ),
        migrations.RenameField(
            model_name='childhealthinfo',
            old_name='vac',
            new_name='deworming2',
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='fic',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=10),
        ),
    ]
