# Generated by Django 4.2.3 on 2023-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0007_alter_primarychild_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatechild',
            name='isDuplicate',
            field=models.BooleanField(default=False),
        ),
    ]
