# Generated by Django 4.2.3 on 2023-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0007_rename_first_name_child_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='firstName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
