# Generated by Django 4.2.3 on 2023-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0007_forms_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Not specified', max_length=10),
        ),
    ]
