# Generated by Django 4.2.3 on 2023-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0008_primarychild_caregiverethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarychild',
            name='lengthOfStay',
            field=models.CharField(default='Not specified', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='lengthOfStayType',
            field=models.CharField(choices=[('Year/s', 'Year/s'), ('Month/s', 'Month/s'), ('Week/s', 'Week/s')], default='Not specified', max_length=100, null=True),
        ),
    ]
