# Generated by Django 4.2.3 on 2023-10-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0008_rename_weightforage_firstquarter_weightforagestatusstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstquarter',
            old_name='weightForAgeStatusStatus',
            new_name='weightForAgeStatus',
        ),
    ]
