# Generated by Django 4.2.3 on 2023-11-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0008_remove_primarychild_dow_childhealthinfo_dow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='child',
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='child_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_form.primarychild'),
        ),
        migrations.AlterField(
            model_name='primarychild',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='quarter_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_form.quarter'),
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='year_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_form.year'),
        ),
    ]
