# Generated by Django 4.2.3 on 2023-11-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0008_alter_child_firstname_alter_child_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
