# Generated by Django 4.2.3 on 2023-10-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0009_rename_weightforagestatusstatus_firstquarter_weightforagestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstquarter',
            old_name='weightForlength',
            new_name='weigthForLengthStatus',
        ),
        migrations.RenameField(
            model_name='fourthquarter',
            old_name='weightForLength',
            new_name='weigthForLengthStatus',
        ),
        migrations.RenameField(
            model_name='secondquarter',
            old_name='weightForlength',
            new_name='weigthForLengthStatus',
        ),
        migrations.RenameField(
            model_name='thirdquarter',
            old_name='weightForlength',
            new_name='weigthForLengthStatus',
        ),
    ]
