# Generated by Django 4.2.3 on 2023-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0009_forms_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='bpe',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='forms',
            name='disability',
            field=models.CharField(default='', max_length=50),
        ),
    ]
