# Generated by Django 4.2.3 on 2023-11-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0010_firstquarter_fourthquarter_secondquarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquarter',
            name='child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.primarychild'),
        ),
        migrations.AlterField(
            model_name='fourthquarter',
            name='child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.primarychild'),
        ),
        migrations.AlterField(
            model_name='secondquarter',
            name='child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.primarychild'),
        ),
        migrations.AlterField(
            model_name='thirdquarter',
            name='child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.primarychild'),
        ),
    ]
