# Generated by Django 4.2.3 on 2023-10-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0010_rename_weightforlength_firstquarter_weigthforlengthstatus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='secondQuarter',
            new_name='Child',
        ),
        migrations.DeleteModel(
            name='firstQuarter',
        ),
        migrations.DeleteModel(
            name='fourthQuarter',
        ),
        migrations.DeleteModel(
            name='thirdQuarter',
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child'},
        ),
    ]
