# Generated by Django 4.2.3 on 2023-10-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0011_forms_father_ethnicity_forms_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='dow',
            field=models.DateField(blank=True, null=True),
        ),
    ]
