# Generated by Django 4.2.3 on 2023-11-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0011_alter_firstquarter_child_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildHealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('muac', models.FloatField(default=0)),
                ('purga', models.DateField(blank=True, null=True)),
                ('vac', models.DateField(blank=True, null=True)),
                ('bpe', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=10)),
                ('disability', models.CharField(blank=True, default='', max_length=50)),
                ('quarter', models.CharField(default='firstquarter', max_length=20)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_form.primarychild')),
            ],
        ),
        migrations.RemoveField(
            model_name='fourthquarter',
            name='child_id',
        ),
        migrations.RemoveField(
            model_name='secondquarter',
            name='child_id',
        ),
        migrations.RemoveField(
            model_name='thirdquarter',
            name='child_id',
        ),
        migrations.DeleteModel(
            name='firstQuarter',
        ),
        migrations.DeleteModel(
            name='fourthQuarter',
        ),
        migrations.DeleteModel(
            name='secondQuarter',
        ),
        migrations.DeleteModel(
            name='thirdQuarter',
        ),
    ]
