# Generated by Django 4.2.3 on 2023-10-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0012_forms_dow'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='weight',
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
