# Generated by Django 4.2.3 on 2023-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0013_forms_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='height',
            field=models.FloatField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='forms',
            name='midUpperArmCircumference',
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
