# Generated by Django 4.2.3 on 2023-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0014_forms_height_forms_midupperarmcircumference'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='purga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='vac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
