# Generated by Django 4.2.3 on 2023-11-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0014_rename_child_id_childhealthinfo_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childhealthinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='childhealthinfo',
            name='childHealth_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
