# Generated by Django 4.2.3 on 2023-11-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0015_remove_childhealthinfo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childhealthinfo',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
