# Generated by Django 4.2.3 on 2023-11-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0016_childhealthinfo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childhealthinfo',
            name='quarter',
            field=models.CharField(default='1st Quarter', max_length=20),
        ),
    ]
