# Generated by Django 4.2.3 on 2023-11-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0017_alter_childhealthinfo_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='childhealthinfo',
            name='getYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
