# Generated by Django 4.2.3 on 2023-10-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0021_alter_forms_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='temporary',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default='', max_length=30),
        ),
    ]
