# Generated by Django 4.2.3 on 2023-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0022_alter_forms_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='aim',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
