# Generated by Django 4.2.3 on 2023-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0023_forms_aim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='aim',
            field=models.IntegerField(default=0),
        ),
    ]
