# Generated by Django 4.2.3 on 2023-10-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0024_alter_forms_aim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='father_ethnicity',
            new_name='parent_ethnicity',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='father_name',
            new_name='parent_name',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='father_occupation',
            new_name='parent_occupation',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='mother_ethnicity',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='mother_occupation',
        ),
    ]
