# Generated by Django 4.2.3 on 2023-10-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0025_rename_father_ethnicity_forms_parent_ethnicity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
