# Generated by Django 4.2.3 on 2023-10-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0026_forms_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
