# Generated by Django 4.2.3 on 2023-10-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0027_alter_forms_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='parent_relation',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Not specified', max_length=10),
        ),
    ]
