# Generated by Django 4.2.3 on 2023-10-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0028_forms_parent_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='parent_relation',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], default='Not specified', max_length=10),
        ),
    ]
