# Generated by Django 4.2.3 on 2023-10-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0029_alter_forms_parent_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='banrangay',
            field=models.CharField(choices=[('Alapang', 'Alapang'), ('Alno', 'Alno'), ('Ambiong', 'Ambiong'), ('Balili', 'Balili'), ('Bahong', 'Bahong'), ('Beckel', 'Beckel'), ('Betag', 'Betag'), ('Bineng', 'Bineng'), ('Cruz', 'Cruz'), ('Lubas', 'Lubas'), ('Pico', 'Pico'), ('Poblacion', 'Poblacion'), ('Puguis', 'Puguis'), ('Shilan', 'Shilan'), ('Tawang', 'Tawang'), ('Wangal', 'Wangal')], default='Not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='forms',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
