# Generated by Django 4.2.3 on 2023-10-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0031_rename_banrangay_forms_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='sitio',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
