# Generated by Django 4.2.3 on 2023-10-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0032_forms_sitio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='date_added',
            new_name='current_date',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='midUpperArmCircumference',
            new_name='muac',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='parent_relation',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='temporary',
        ),
        migrations.AddField(
            model_name='forms',
            name='pt',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='forms',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], default='Not specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='forms',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Not specified', max_length=10),
        ),
    ]
