# Generated by Django 4.2.6 on 2023-10-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='barangay',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='job_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
