# Generated by Django 4.2.6 on 2023-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
