# Generated by Django 4.2.6 on 2023-10-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_useraccount_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
