# Generated by Django 4.2.6 on 2023-11-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0004_useraccount_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
