# Generated by Django 4.2.6 on 2023-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0005_alter_useraccount_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
