const ethnicityOptions =[
    'Aggay',
    'Akeanon/Aklanon',
    'Apayao/Yapayao',
    'Ayangan',
    'Balangao/Baliwon',
    'Bikol/Bicol',
    'Bisaya/Binisaya',
    'Bontok/Binontok',
    'Cebuano',
    'Hamtikanon',
    'Hiligaynon,Ilonggo',
    'Ibaloi/Inibaloi',
    'Ibanag',
    'Ibontoc',
    'Ifugao',
    'Kalanguya/Ikalahan',
    'Ilocano',
    'Iranon',
    'Itneg',
    'Kalinga',
    'Kankanai/Kankanaey',
    'Kapampangan',
    'Karao',
    'Kinalinga',
    'Kiniray-a',
    'Maranao',
    'Masbateno/Masbatean',
    'Pangasinan/Panggalato',
    'Surigaonon',
    'Tagalog',
    'Tausug',
    'Waray',
    'Other Local Ethnicity',
    'Chinese',
    'American/English',
    'Other Foreign Ethnicity',
    'Not Reported',
  ];

  export default ethnicityOptions;