const ethnicityOptions = [
  "Others",
  "Aggay",
  "Akeanon/Aklanon",
  "Apayao/Yapayao",
  "Ayangan",
  "Balangao/Baliwon",
  "Bikol/Bicol",
  "Bisaya/Binisaya",
  "Bontok/Binontok",
  "Cebuano",
  "Hamtikanon",
  "Hiligaynon,Ilonggo",
  "Ibaloi/Inibaloi",
  "Ibanag",
  "Ibontoc",
  "Ifugao",
  "Kalanguya/Ikalahan",
  "Ilocano",
  "Iranon",
  "Itneg",
  "Kalinga",
  "Kankanai/Kankanaey",
  "Kapampangan",
  "Karao",
  "Kinalinga",
  "Kiniray-a",
  "Maranao",
  "Masbateno/Masbatean",
  "Pangasinan/Panggalato",
  "Surigaonon",
  "Tagalog",
  "Tausug",
  "Waray",
  "Not specified",
];
const uppercaseEthnicityOptions = ethnicityOptions.map((option) =>
  option.toUpperCase()
);

export default uppercaseEthnicityOptions;
