# Generated by Django 4.2.5 on 2023-09-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
